<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Composa</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="$(SkiaSharpVersion)" />
    <InternalsVisibleTo Include="Composa.Core.Tests" />
  </ItemGroup>
</Project>
